# services:

  # mysql:
  #   image: mysql:8.0
  #   container_name: mamba-mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: mamba_db
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: user
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql-data:/var/lib/mysql

  # mongo:
  #   image: mongo:8.0
  #   container_name: mamba-mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db

# volumes:
  # mysql-data:
    # mongo-data:
