spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mamba_db
    username: root
    password: Cecile12@
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: dsv # Change to 'prd' for production environment

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
    open-in-view: false

  mongodb:
    uri: mongodb://localhost:27017/mamba_mongo
server:
  port: 8080

logging:
  level:
    root: INFO
    '[org.hibernate.SQL]': DEBUG

springdoc: 
  api-docs:
    enabled: true # Change to 'false' to disable Swagger in production
  swagger-ui:
    enabled: true # Change to 'false' to disable Swagger in production